In [1]:
# pipenv install pandas scipy tensorboard plotly scikit-learn catboost shap ipykernel ipywidgets nbformat

# EDA & Data Preparation
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency,f_oneway, ttest_ind
from colorama import Fore, Back, Style
import plotly.express as px
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

# ML
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay, log_loss, roc_curve, roc_auc_score

# Interpretability
import shap

# Data Preparation

In [13]:
df_companies = pd.read_csv('./datasets/companies_profile.csv')
df_companies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     1000 non-null   int64
 1   Company_Name           1000 non-null   str
 2   Annual_Revenue         1000 non-null   int64
 3   Net_Margin             1000 non-null   float64
 4   Debt_Level             1000 non-null   float64
 5   Industry               1000 non-null   str
 6   Region                 1000 non-null   str
 7   Years_in_Business      1000 non-null   int64
 8    External_Audit        1000 non-null   int64
 9   Credit_Rating          1000 non-null   float64
 10  Company_Type           1000 non-null   str
 11  Sustainability_Policy  1000 non-null   str
 12  Expansion_Strategy     1000 non-null   str
 13  Risk_Management        1000 non-null   str
 14  Insurance_Coverage     654 non-null    str
 15  Digital_Maturity       1000 non-null   str
 16  Corporate_Governance   1000 non-null   str
 17  Innovation_Culture     1000 non-null   str
 18  Community_Relations    1000 non-null   str
 19  Credit_Risk            1000 non-null   int64
 20  Compliance_Risk        1000 non-null   int64
 21  Market_Risk            1000 non-null   int64
dtypes: float64(3), int64(7), str(12)
memory usage: 172.0 KB

In [15]:
df_companies.head(10)

,ID,Company_Name,Annual_Revenue,Net_Margin,Debt_Level,Industry,Region,Years_in_Business,External_Audit,Credit_Rating,...,Expansion_Strategy,Risk_Management,Insurance_Coverage,Digital_Maturity,Corporate_Governance,Innovation_Culture,Community_Relations,Credit_Risk,Compliance_Risk,Market_Risk
0,1,Hahn Group,6523388,0.482879,1.032767,Manufacturing,Europe,26,0,0.938715,...,Partnerships,Centralized,Basic,Advanced,Low,Neutral,Average,0,0,0
1,2,Lopez Group,6650634,0.121292,0.492841,Technology,Europe,20,1,0.492362,...,Organic,Centralized,Basic,Beginner,Medium,Neutral,Poor,0,0,0
2,3,Sparks and Sons,4404572,0.190114,0.757099,Manufacturing,Latin America,6,0,0.700866,...,Organic,Decentralized,Basic,Beginner,High,Neutral,Good,0,0,0
3,4,"Fields, Ramirez and Craig",2334489,0.402442,2.327962,Manufacturing,Europe,6,1,0.855551,...,Partnerships,Centralized,NaN,Intermediate,Medium,Innovative,Excellent,1,0,0
4,5,"Campbell, Hernandez and Lyons",9624682,0.174549,1.722357,Healthcare,North America,18,1,0.418291,...,Acquisitions,Decentralized,NaN,Advanced,Low,Neutral,Average,0,0,0
5,6,Robinson Ltd,7304212,-0.070876,1.290515,Healthcare,North America,4,1,0.309413,...,Organic,Centralized,Comprehensive,Advanced,High,Neutral,Poor,1,0,1
6,7,Bennett LLC,9728519,0.009717,0.130516,Technology,Asia,17,0,0.936725,...,Partnerships,Decentralized,Basic,Advanced,Medium,Neutral,Average,0,1,0
7,8,"Rios, Stevens and Johnson",4572471,0.016956,2.481797,Healthcare,Europe,14,1,0.515677,...,Partnerships,Centralized,NaN,Intermediate,High,Neutral,Average,1,0,0
8,9,"Murphy, Walters and Cruz",4623669,0.078123,1.711492,Technology,Latin America,14,0,0.497254,...,Acquisitions,Decentralized,Basic,Advanced,Medium,Neutral,Poor,0,1,0
9,10,Larson Ltd,7504852,0.098752,0.860614,Finance,Latin America,13,0,0.178416,...,Acquisitions,Centralized,Basic,Intermediate,Medium,Conservative,Good,1,1,0

In [16]:
df_companies.describe()

,ID,Annual_Revenue,Net_Margin,Debt_Level,Years_in_Business,External_Audit,Credit_Rating,Credit_Risk,Compliance_Risk,Market_Risk
count,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,4.992928e+06,0.152379,1.317909,25.367000,0.496000,0.487000,0.595000,0.206000,0.110000
std,288.819436,2.804931e+06,0.199511,0.700616,14.103873,0.500234,0.292846,0.491138,0.404633,0.313046
min,1.000000,1.393530e+05,-0.199834,0.100452,1.000000,0.000000,0.000748,0.000000,0.000000,0.000000
25%,250.750000,2.646178e+06,-0.021089,0.691918,13.000000,0.000000,0.232142,0.000000,0.000000,0.000000
50%,500.500000,5.032603e+06,0.160441,1.364206,25.000000,0.000000,0.475893,1.000000,0.000000,0.000000
75%,750.250000,7.270658e+06,0.323736,1.919788,38.000000,1.000000,0.742092,1.000000,0.000000,0.000000
max,1000.000000,9.989550e+06,0.499547,2.499313,49.000000,1.000000,0.999049,1.000000,1.000000,1.000000